server:
  port: 8081
spring:
  application:
    name: getsway-service-lee
eureka:
  client:
    service-url:
      defaultZone: https://eureka.leesh.top/eureka
#zuul:
#  routes:
#    my-roul:
#      service-id:
#      path: